# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJUBiLBqHl4zd3_xVot5pWac-kzHv-Ir
"""

students = []
courses = []
marks = {}

def input_number_students():
    """Input number of students in a class"""
    while True:
        try:
            n = int(input("Enter the number of students in the class: "))
            if n > 0:
                return n
            print("Number of students must be greater than 0.")
        except ValueError:
            print("Invalid input. Please enter an integer.")

def input_student_info(num_students):
    """Input student information: id, name, DoB"""
    print("\n--- Enter Student Information ---")
    for _ in range(num_students):
        student_id = input("Enter student ID: ")
        name = input("Enter student name: ")
        dob = input("Enter student DoB (DD/MM/YYYY): ")
        students.append({'id': student_id, 'name': name, 'dob': dob})

def input_number_courses():
    """Input number of courses"""
    while True:
        try:
            n = int(input("\nEnter the number of courses: "))
            if n > 0:
                return n
            print("Number of courses must be greater than 0.")
        except ValueError:
            print("Invalid input. Please enter an integer.")

def input_course_info(num_courses):
    """Input course information: id, name"""
    print("\n--- Enter Course Information ---")
    for _ in range(num_courses):
        course_id = input("Enter course ID: ")
        name = input("Enter course name: ")
        courses.append({'id': course_id, 'name': name})
        marks[course_id] = {}

def input_marks():
    """Select a course, input marks for student in this course"""
    if not courses:
        print("No courses available! Please add courses first.")
        return
    if not students:
        print("No students available! Please add students first.")
        return

    list_courses()
    course_id = input("\nSelect a course ID to input marks: ")

    course_ids = [c['id'] for c in courses]
    if course_id not in course_ids:
        print("Course not found!")
        return

    print(f"\n--- Inputting marks for course {course_id} ---")
    for s in students:
        while True:
            try:
                mark = float(input(f"Enter mark for student {s['name']} (ID: {s['id']}): "))
                if 0 <= mark <= 20:
                    marks[course_id][s['id']] = mark
                    break
                print("Mark must be between 0 and 20.")
            except ValueError:
                print("Invalid input. Please enter a valid number.")

def list_courses():
    """List courses"""
    print("\n--- List of Courses ---")
    if not courses:
        print("Empty.")
    for c in courses:
        print(f"ID: {c['id']} | Name: {c['name']}")

def list_students():
    """List students"""
    print("\n--- List of Students ---")
    if not students:
        print("Empty.")
    for s in students:
        print(f"ID: {s['id']} | Name: {s['name']} | DoB: {s['dob']}")

def show_student_marks():
    """Show student marks for a given course"""
    if not courses:
        print("No courses available.")
        return

    list_courses()
    course_id = input("\nSelect a course ID to view marks: ")

    course_ids = [c['id'] for c in courses]
    if course_id not in course_ids:
        print("Course not found!")
        return

    print(f"\n--- Marks for course {course_id} ---")
    course_marks = marks.get(course_id, {})

    if not course_marks:
        print("No marks have been inputted for this course yet.")
    else:
        for s in students:
            s_id = s['id']
            mark = course_marks.get(s_id, "N/A")
            print(f"Student: {s['name']} (ID: {s_id}) -> Mark: {mark}")

def main():
    num_students = input_number_students()
    input_student_info(num_students)

    num_courses = input_number_courses()
    input_course_info(num_courses)

    while True:
        print("\n" + "="*30)
        print("STUDENT MARK MANAGEMENT SYSTEM")
        print("1. List all courses")
        print("2. List all students")
        print("3. Input marks for a course")
        print("4. Show student marks for a given course")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            list_courses()
        elif choice == '2':
            list_students()
        elif choice == '3':
            input_marks()
        elif choice == '4':
            show_student_marks()
        elif choice == '5':
            print("Exiting program...")
            break
        else:
            print("Invalid choice! Please try again.")

if __name__ == "__main__":
    main()