# -*- coding: utf-8 -*-
"""labwork1a.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vznQbh8Ze1-bHc8xz957eJTIRkEpszX
"""

radius = float(input("Enter circle radius? "))
area = math.pi * (radius ** 2)
print(f"Circle area ={area}")

celsius = float(input("Enter the temperature in Celsius? "))
fahrenheit = (celsius * 9 / 5) + 32
print(f"{int(celsius)} (C)={fahrenheit} (F)")

n = int(input("Enter a number? "))
if n > 1 and all(n % i != 0 for i in range(2, int(n**0.5) + 1)):
  print(f"{n} is a prime number")
else:
  print(f"{n} is a NOT prime number")

n = int(input("Enter a number? "))

sum_divisors = 0

for i in range(1, n):
    if n % i == 0:
        sum_divisors += i

if sum_divisors == n and n > 0:
    print(f"{n} is a perfect number")
else:
    print(f"{n} is a NOT perfect number")

colors = ["Blue", "Yellow", "Black", "Red", "White"]

user_color = input("What is your favorite color? ")

if user_color in colors:
    print(f"Your colod is at index {colors.index(user_color)} in my list")
else:
    print("Sorry, I could not find your color")

# range1: 0, 1, 2, 3, 4, 5, 6
range1 = list(range(0, 7))
print("range1:", range1)

# range2: 1, 4, 7, 10
range2 = list(range(1, 11, 3))
print("range2:", range2)

# range3: 5, 4, 3, 2, 1
range3 = list(range(5, 0, -1))
print("range3:", range3)

# range4: 6, 4, 2, 0, -2
range4 = list(range(6, -3, -2))
print("range4:", range4)

def remove_dollar_sign(s):
    return s.replace("$", "")
print(remove_dollar_sign("$100"))

def extract_even(l):
    return [x for x in l if x % 2 == 0]


# For testing
if __name__ == "__main__":
    sample_list = [1, 4, 5, -1, 10]
    result = extract_even(sample_list)

    print("Original list:", sample_list)
    print("Extracted even numbers:", result)

def factorial(n):
    if n < 0:
        return None
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result
num = int(input("Enter a number: "))
print(factorial(num))

def get_divisors(n):
    return [i for i in range(1, n + 1) if n % i == 0]

# For Testing
number = int(input("Enter a number? "))
divisors = get_divisors(number)
print(f"Divisors of {number} are: {divisors}")

x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))
x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))

distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print(f"Distance between points: {distance}")

def print_pattern(m, n):
    for i in range(m):
        print("*" * n)